### ISSUE TITLE
Devices keeps Opening... or Closing... 

### ISSUE THREAD

**Issue by QempZor** [jhurliman/homebridge-motionblinds#12]
The blinds keeps their status on Opening.... or Closing... in the Home app.
They respond, but they still keep showing opening or closing, even when they done setting up the position.
![image](https://user-images.githubusercontent.com/35775426/161292312-8ccf61ba-71ce-458f-8ab4-2c74dc67fecf.png)

Logs warning appears:
[4/1/2022, 5:12:57 PM] [homebridge-motionblinds] This plugin generated a warning from the characteristic 'Target Position': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

**Comment by jhurliman** [comment]
This should be improved in 2.0.0, please give it a try and reopen if you encounter issues. I still see a delay of about 10 seconds in the Home app before the Opening/Closing state goes away, and I can't seem to overcome it. It could be a limitation in homebridge / HapJS / HomeKit / Home app.

**Comment by QempZor** [comment]
Thanks for the update! Keep up the good work.
However; Im still encoutering this problem. Even aftyer updating to 2.0.0. 

After closing or opening the blind sometimes says it's closed or open; but changing the position to another percentage it wont work. Video: https://youtu.be/qRbW7AYEii0

Any tips I can try?

EDIT: I used to use the motionblinds homeassistant plugin to expose the blinds in HomeAssistant and then use the Homeassistant Homekit plugin to expose the HomeAssistant entities to HomeKit. That way it works correctly. But that was the only plugin I use in homeassistant so I want to get rid of HA :)

**Comment by jakatt** [comment]
Thanks for the update indeed. Now invert mode works perfectly which was not the case in previous version.

However blinds keeps "OPENING" forever in HOMEKIT since upgrade which was not the case in previous version.
Status works very OK in Homebridge itself, just the update in HomeKit not working properly.

Any suggestions ?

**Comment by aequitas** [comment]
Also running into this issue. I'm on version 2.0.0 from the start. The accessory keep in the "Opening..." or "Closing..." state, even after restarting the blind, bridge or homebridge plugin.

**Comment by nanonansen** [comment]
Same for me.

**Comment by joeblack2k** [comment]
Same here, same log

**Comment by nanonansen** [comment]
Also just now realized it only happens for me when inverted=true. When not inverted homekit works as expected (just opening / closing states are wrong)
