### ISSUE TITLE
Motion Bridge keeps appearing as device

### ISSUE THREAD

**Issue by eqsone** [jhurliman/homebridge-motionblinds#16]
Recently the Motion Bridge itself keeps appearing as device in Homebridge and Home App. It gets named by its 12-digit MAC address along with a permanent low battery warning.

**Comment by ddalbroi** [comment]
I also discovered the same issue with my DD7002B bridge.

I added/replaced the following code into async discoverDevices() in platform.js to workaround the issue.             

          for (const device of devices) {
                // Do not add the bridge as an accessory
		if (device.mac.length == 16) {
			this.maybeAddOrUpdateAccessory(device.mac, device.deviceType, device.data);
		}
            }

Would be good if this procedure was updated in the master branch.. or do a length check elsewhere if there is a better way of doing it

**Comment by eqsone** [comment]
Nice one, thanks a lot!

**Comment by eqsone** [comment]
Ugh, happy too soon. The gateway disappears from the list of devices at first, then for some reason it adds back in after about 10 minutes. Tried using strict equality operators (===) instead but it didn‘t make a difference. It happens with both ways, filtering for the mac as well as checking for the length.

**Comment by ddalbroi** [comment]
You might need to remove the bridge in your homebridge cache after applying the change. It’s in homebridge settings via the UI. Apply the code change, remove the accessory from the cache then restart homebridge or the child bridge

Following that order worked for me

**Comment by eqsone** [comment]
Thanks for the suggestion, that‘s what I did first of all, but I‘ll double check the cache again.

**Comment by eqsone** [comment]
Checked again. Even with cache fully cleared, the gateway still gets added after a while as new accessory, followed by the well known bunch of warning entries because it doesn't provide the expected blind values:

`[28/06/2022, 16:37:47] [MOTION Blinds] Adding new accessory: a4cf12fecaa8`
`[a4cf12fecaa8@@Model] characteristic value expected string and received undefined`
`[28/06/2022, 16:37:52] [homebridge-motionblinds] This plugin generated a warning from the characteristic 'Current Position': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.`
`[28/06/2022, 16:37:52] [homebridge-motionblinds] This plugin generated a warning from the characteristic 'Target Position': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.`
`[28/06/2022, 16:38:38] [homebridge-motionblinds] This plugin generated a warning from the characteristic 'Current Position': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.`
[...]

**Comment by ddalbroi** [comment]
that's odd..

you could try isolating it down the in the addAccessory function by adding something like this to the top of it, to ensure the bridge is never added.

if (mac.length != 16) {
		return;
}

or

if (mac == "a4cf12fecaa8") {
		return;
}


This was where I originally started, but thought it was cleaner to isolate the bridge in the discoverDevices function

**Comment by eqsone** [comment]
You were right, this was cache related. The Homebridge UI left some data in `~/.homebridge/accessories/cachedAccessories` though this should have been empty. Cleared them manually from the command line and the gateway didn’t show up again. 
Thanks for your support!

**Comment by eqsone** [comment]
Wow, it stays odd. About 24 hours after my last post the bridge popped back in, added as new accessory.

So still in `platform.js` in function `maybeAddOrUpdateAccessory(mac, deviceType, status) {}` I modded the else part of `if (existingAccessory) {}` into this:

```
else {
    if (deviceType !== 'Gateway') {
        this.log.info(`Adding new accessory: mac=${mac}, uuid=${uuid}, deviceType=${motionblinds_1.DEVICE_TYPES[deviceType]}, status=${JSON.stringify(status)}`);
        this.addAccessory(mac, uuid, deviceType, status);
    }
}
```

The bridge was kept out since then but it's not been 24 hours, yet. I'll report back if returns.
___

EDIT: Err, nope. The gateway stays out but now it throwed following -quite obvious- error leading to shutdown and restart homebridge:
```
[30/06/2022, 21:26:27] ReferenceError: Gateway is not defined
    at MotionBlindsPlatform.maybeAddOrUpdateAccessory (/usr/local/lib/node_modules/homebridge-motionblinds/src/platform.ts:127:6)
```

**Comment by eqsone** [comment]
New attempt, contains your suggested return command, promising so far:

```
for (const device of devices) {
    if (device.deviceType !== 'Gateway’) {
        this.maybeAddOrUpdateAccessory(device.mac, device.deviceType, device.data);
    }
    else return;
}
```
___

EDIT: Bridge was added again, starting next attempt..

**Comment by jhurliman** [comment]
Thanks for digging into this, I’m on vacation at the moment and when I return I will incorporate this fix. I run into the same issue with my setup at home, it will be great to have it fixed.

**Comment by eqsone** [comment]
That’s great news, you‘re very welcome.

**Comment by eqsone** [comment]
This finally works durable within my setup: Modding in `platform.js` in function `maybeAddOrUpdateAccessory(mac, deviceType, status)` the else part of `if (existingAccessory)` like this i.e.:

```
else {
    this.log.info(`Found new accessory: mac=${mac}, uuid=${uuid}, deviceType=${motionblinds_1.DEVICE_TYPES[deviceType]}, status=${JSON.stringify(status)}`);
    if (motionblinds_1.DEVICE_TYPES[deviceType] != 'Gateway') {
        this.addAccessory(mac, uuid, deviceType, status);
    }
    else {
        this.log.info(`Keeping ${motionblinds_1.DEVICE_TYPES[deviceType]} separate`);
    }
}
```
