### ISSUE TITLE
Blinds not appearing

### ISSUE THREAD

**Issue by saxopwn** [jhurliman/homebridge-motionblinds#2]
Maybe I’m missing something- configured the plug-in using the UI and added the key from the app. Should the blinds show up as accessories in the Home app now? I see the note about MAC addresses but I’m not sure how to get them.

**Comment by saxopwn** [comment]
```
[17/03/2021, 11:28:15] [MOTION Blinds] Failed fetching list of MOTION Blinds: Error: timed out after 3 seconds
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-motionblinds/node_modules/motionblinds/src/index.ts:364:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

Seeing the above error. My setup shouldn't be too weird- Blinds are on a UniFi network using an Apple TV 4K as my only hub. Only weird part was I had to disable my 5 GHz network to set up the MOTION hub originally. No fixed IPs.

**Comment by ghost** [comment]
Had the same issue as you had. I’m also running UniFi. It was solved by putting the Motion hub at the same network as homebridge.

Also, if you are running the plugging as Child Node, you need to scan the QR code provided by homebridge.

Cheers.

**Comment by jhurliman** [comment]
Thanks for the troubleshooting hints. Also, the latest version 1.2.0 includes a networking fix that should get the plugin working for most configurations.
