### ISSUE TITLE
Roller blind changes status only after a few minutes

### ISSUE THREAD

**Issue by Swuffi** [jhurliman/homebridge-motionblinds#4]
I have filled in the fields "platform" and "mac". 
Also I entered the key from the app. However, nothing happens when I click on the device. It changes its state (closed/open) but it does not start up or shut down. If I close the blind with the app, the correct status is displayed after a short time, but they still do not respond via Homebridge.  I also don't get any error messages via the console.

Could still observe the following.
After pressing the switch, the roller blind moves to its desired position. But before I can move the roller blind again in the other direction, a few minutes must have passed.

**Comment by jhurliman** [comment]
Please try again with version 1.2.0

**Comment by Swuffi** [comment]
With this it works. Thanks
