### ISSUE TITLE
Version 1.1: Failed fetching list of MOTION Blinds

### ISSUE THREAD

**Issue by ghost** [jhurliman/homebridge-motionblinds#5]
Hi mate,

  Thanks a lot for your effort in writting this up.

I have updated to version 1.1 just now and noticed the following error everytime:

Failed fetching list of MOTION Blinds: Error: timed out after 3 seconds
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-motionblinds/node_modules/motionblinds/src/index.ts:414:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

Not sure if related but at the IOS home APP the roller status would appear all the time as Closing/Opening after the roller finished in performing the movement.

I hope this helps for the next iteration. It is nearly to be perfect :)

Thanks.

**Comment by jhurliman** [comment]
Did you specify `gatewayIp` or leave it out? And do you know if the computer running Homebridge has more than one network interface?

**Comment by ghost** [comment]
Thanks a lot for the swift reply!

- I tried with and without GatewayIp. Same behavior.
- Only one interface via LAN. WLAN is off.

**Comment by jhurliman** [comment]
Please try again with the latest 1.2.0 release.

**Comment by jhurliman** [comment]
Assuming fixed with the latest release. Please reopen if you are still experiencing this issue.
