### ISSUE TITLE
Can see blinds in HomeKit but not responding

### ISSUE THREAD

**Issue by splashgordon10** [jhurliman/homebridge-motionblinds#6]
I have installed your very useful plugin and have setup the MOTION USB bridge.  I am able to control the blinds via the MOTION iOS App, but not via HomeKit.

The 3 blinds all appear in HomeKit (due to your code) but whenever I try to control them, nothing happens.  I have tried playing around with the "gatewayIp" address (and removing it entirely) but still no luck.

Any suggestions would be very welcomed!

**Comment by gojkop** [comment]
Same problem here... sometimes they work (generally after restarting of the home bridge) and then they just stop working.
The only error visible is this:
`[6/16/2021, 1:22:35 PM] [homebridge-motionblinds] This plugin generated a warning from the characteristic 'Target Position': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.`

`[6/16/2021, 1:22:35 PM] [homebridge-motionblinds] This plugin generated a warning from the characteristic 'Target Position': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.`

The issue persists even with the separate gateway.

**Comment by jhurliman** [comment]
I just pushed a new version that may address the issue, please try updating to 1.2.0 and report back.

**Comment by ronaldsiesta** [comment]
I have just add the plugin to HB. but without succes :(, i get the same massage: [homebridge-motionblinds] This plugin threw an error from the characteristic 'Target Position': Unhandled error thrown inside write handler for characteristic: Invalid key length. See https://git.io/JtMGR for more info.

also in the home app there is no connection.

**Comment by jhurliman** [comment]
This issue should be fixed in 2.0.0. Please reopen if you still encounter the issue.
