### ISSUE TITLE
Invert Window Orientation not works

### ISSUE THREAD

**Issue by floppy007** [jhurliman/homebridge-motionblinds#9]
The invert function is not working. No matter if I turn it on or not. When it should close it opens and when it should open it closes.

**Comment by jakatt** [comment]
Same issue

**Comment by eqsone** [comment]
EDIT | Similar issue: After manually editing false to true the movement got actually inverted. But when the blind is fully closed or opened HomeKit thinks it's still moving. Must be related to the reported 'current state', which is not inverted and therfore never reached.

With physically fully closed blinds, Homebridge shows:

Current Position | 100% (in Apple speech = opened, in MOTION speech = closed)
Position State | 2 (for both this means stop/stopped)
Target Position | 0% (in Apple speech = closed, in MOTION speech = opened)

The traget position is inverted but the current position is not, so Homekit keeps on spinning it's wheel and shows 'closing' like forever.

**Comment by eqsone** [comment]
Editing 'platformAccessory.js' to invert the reported open/closed values seems to fix the above mentioned issue:

// .on('get', (callback) => callback(null, this.status.currentPosition));
.on('get', (callback) => callback(null, 100 - this.status.currentPosition));

The plugin also constantly throwed errors about the targetPosition being undefined. Changing 'const' to 'let' seems to fix this:

// const targetPosition = value;
// const effectiveTarget = this.config.invert ? 100 - targetPosition : targetPosition;
let targetPosition = value;
let effectiveTarget = this.config.invert ? 100 - targetPosition : targetPosition;

Now it still throws readDevice-timeout-errors after moving the blinds, couldn't figure out how to fix by now.

**Comment by jhurliman** [comment]
These issues should be fixed in 2.0.0. Please reopen the issue if you still encounter problems.
